version: "3.7"
services:

  redis:
    container_name: redis
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  flask_app:
    container_name: flask_app
    build: './flask-app'
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis

  background_worker:
    container_name: background_worker
    build: './background-worker'
    user: nobody
    depends_on:
      - redis
      - flask_app

  
